language: ruby

services:
- docker

before_install:
- docker pull nginx/latest
- docker run -d -p 127.0.0.1:80:4567 nginx/latest /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
- docker ps -a
- docker run nginx/latest /bin/sh -c "cd /root/sinatra; bundle exec rake test"
