version: 2
jobs:
  build:
    docker:
      - image: nginx:latest

    steps:
      - checkout

      - run:
          name: Echo contents of /etc/nginx/nginx.conf
          command: cat /etc/nginx/nginx.conf

      - run:
          name: Print the Current Time
          command: date
